version: '2.1'
services:
  zookeeper:
    container_name: dfd-zookeeper
    image: imjaden/zookeeper:3.7.0
    ports:
      - "2181:2181"
  jobmanager:
    container_name: dfd-jobmanager
    image: flink:1.14.0-scala_2.11
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  taskmanager:
    container_name: dfd-taskmanager
    image: flink:1.14.0-scala_2.11
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
  kafka:
    container_name: dfd-kafka
    image: imjaden/kafka:2.13-2.7.2
    ports:
      - "9092:9092"
      - "9094:9094"
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://:9094,OUTSIDE://localhost:9092
      - KAFKA_LISTENERS=INSIDE://:9094,OUTSIDE://:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=source001:1:1,sink001:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  flink:
    container_name: dfd-flink
    image: imjaden/flink:2.12-1.14.0
    depends_on:
      - kafka
      - jobmanager
    environment:
      FLINK_JOBMANAGER_HOST: jobmanager
      ZOOKEEPER_CONNECT: zookeeper
      KAFKA_BOOTSTRAP: kafka
  
networks:
  default:
    name: dfd-networkd
    driver: bridge
